title: "The Failed Astrophysicist"
tagline: "Physicist × Filmmaker × Educator × Writer × Poet"
description: "Exploring universes in science, film, code, and ideas."
url: "https://thefailedastrophysicist.github.io/"
baseurl: ""   # keep empty for user.github.io root sites
permalink: /lessons/:title/


# Default layouts for posts & experience entries
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: "The Failed Astrophysicist"

markdown: kramdown
plugins: []    # keep empty; GitHub Pages will still build this fine
