title: "Cinematic Physics"
description: "Physics is not equations. It's story, intuition, and beauty."
baseurl: ""
url: "https://thefailedastrophysicist.github.io/"

markdown: kramdown
theme: null
plugins: []
